name: Build

on:
  workflow_dispatch:

    inputs:
      shell:
        description: 'shell'
        required: true
        default: 'ls ; '

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        run: |
          cd android
          ./gradlew assembleRelease
     
      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: 上传到release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.PACKAGE_VERSION }}_${{ github.run_number }}"
          name: "${{ env.PACKAGE_VERSION }}_${{ github.run_number }}"
          body: |
            version : ${{ env.PACKAGE_VERSION }}
          artifacts: 'android/app/build/outputs/apk/release/*'
